# Generated by Django 5.0.3 on 2024-04-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('depart', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('arrets', models.IntegerField()),
                ('h_depart', models.CharField(max_length=50)),
                ('h_arrivee', models.CharField(max_length=50)),
            ],
        ),
    ]
